import { Theme } from '@fluentui/react-components';

export const brandTheme: Theme = {
  'borderRadiusNone': '0px',
  'borderRadiusSmall': '2px',
  'borderRadiusMedium': '4px',
  'borderRadiusLarge': '6px',
  'borderRadiusXLarge': '8px',
  'borderRadiusCircular': '9999px',
  'fontSize0': '10px',
  'fontSize1': '12px',
  'fontSize2': '14px',
  'fontSize3': '16px',
  'fontSize4': '20px',
  'fontSize5': '24px',
  'fontSize6': '28px',
  'fontSize7': '32px',
  'fontSize8': '40px',
  'fontSize9': '48px',
  'fontSize10': '52px',
  'fontSize1000': '68px',
  'fontSizeBase100': '10px',
  'fontSizeBase200': '12px',
  'fontSizeBase300': '14px',
  'fontSizeBase400': '16px',
  'fontSizeBase500': '20px',
  'fontSizeBase600': '24px',
  'fontSizeBase700': '28px',
  'fontSizeBase800': '32px',
  'fontSizeBase900': '40px',
  'fontSizeBase980': '52px',
  'fontSizeBase920': '48px',
  'lineHeightBase100': '14px',
  'lineHeightBase200': '16px',
  'lineHeightBase300': '22px',
  'lineHeightBase400': '24px',
  'lineHeightBase500': '28px',
  'lineHeightBase600': '34px',
  'lineHeightBase700': '36px',
  'lineHeightBase800': '48px',
  'lineHeightBase900': '52px',
  'lineHeightbase1000': '92px',
  'lineHeightBase920': '64px',
  'lineHeightBase980': '70px',
  'fontFamilyBase': 'Segoe UI',
  'fontWeightRegular': '500',
  'fontWeightSemibold': '600',
  'fontWeightBold': '700',
  'fontWeightSemilight': '300',
  'fontWeightLight': '200',
  'strokeWidthNone': '0px',
  'strokeWidthThin': '1px',
  'strokeWidthThick': '2px',
  'strokeWidthThicker': '4px',
  'strokeWidthThickest': '6px',
  'spacingHorizontalNone': '0px',
  'spacingHorizontalXXS': '2px',
  'spacingHorizontalXS': '4px',
  'spacingHorizontalSNudge': '6px',
  'spacingHorizontalS': '8px',
  'spacingHorizontalMNudge': '12px',
  'spacingHorizontalM': '16px',
  'spacingHorizontalL': '32px',
  'spacingHorizontalXL': '48px',
  'spacingHorizontalXXL': '52px',
  'spacingHorizontalXXXL': '56px',
  'spacingHorizontalLNudge': '24px',
  'spacingHorizontalXXXXL': '64px',
  'spacingVerticalNone': '0px',
  'spacingVerticalXXS': '2px',
  'spacingVerticalXS': '4px',
  'spacingVerticalSNudge': '6px',
  'spacingVerticalS': '8px',
  'spacingVerticalMNudge': '12px',
  'spacingVerticalM': '16px',
  'spacingVerticalL': '32px',
  'spacingVerticalXL': '48px',
  'spacingVerticalXXL': '52px',
  'spacingVerticalXXXL': '56px',
  'spacingVerticalLNudge': '24px',
  'spacingVerticalXXXXL': '64px',
  'colorNeutralBackground1RestLight': '{Colors.Neutral.White}',
  'colorNeutralBackground1HoverLight': '{Colors.Neutral.Grey-80}',
  'colorNeutralBackground1PressedLight': '{Colors.Neutral.Grey-70}',
  'colorNeutralBackground1SelectedLight': '{Colors.Neutral.Grey-90}',
  'colorNeutralBackground2RestLight': '#f5f4f2',
  'colorNeutralBackground3RestLight': '{Colors.Neutral.Grey-70}',
  'colorNeutralBackground3HoverLight': '{Colors.Neutral.Grey-80}',
  'colorNeutralBackground3PressedLight': '{Colors.Neutral.Grey-80}',
  'colorNeutralBackground4RestLight': '{Colors.Neutral.Grey-90}',
  'colorNeutralBackground4HoverLight': '{Colors.Neutral.Grey-70}',
  'colorNeutralBackground4PressedLight': '{Colors.Neutral.Grey-60}',
  'colorNeutralBackground5RestLight': '{Colors.Neutral.Grey-80}',
  'colorNeutralBackground6RestLight': '{Colors.Neutral.Grey-90}',
  'colorNeutralBackgroundInvertedRestLight': '{Brand-10}',
  'colorNeutralBackgroundInvertedDisabledRestLight': '{Colors.Alpha.White.10}',
  'colorNeutralBackgroundAlpha1RestLight': '{Colors.Alpha.White.50}',
  'colorNeutralBackgroundAlpha2RestLight': '{Colors.Alpha.White.80}',
  'colorNeutralBackgroundStaticRestLight': '{Colors.Neutral.White}',
  'colorNeutralBackgroundSubtleRestLight': '{Colors.Alpha.White.0}',
  'colorNeutralBackgroundSubtleHoverLight': '{Colors.Neutral.Grey-80}',
  'colorNeutralBackgroundSubtlePressedLight': '{Colors.Neutral.Grey-70}',
  'colorNeutralBackgroundSubtleSelectedLight': '{Colors.Neutral.Grey-90}',
  'colorNeutralBackgroundSubtleLightAlphaHoverLight': '{Colors.Alpha.White.70}',
  'colorNeutralBackgroundSubtleLightAlphaPressedLight': '{Colors.Alpha.White.50}',
  'colorNeutralBackgroundSubtleLightAlphaSelectedLight': '{Colors.Alpha.White.0}',
  'colorNeutralBackgroundSubtleInvertedRestLight': '{Colors.Alpha.Black.0}',
  'colorNeutralBackgroundSubtleInvertedHoverLight': '{Colors.Alpha.Black.10}',
  'colorNeutralBackgroundSubtleInvertedPressedLight': '{Colors.Alpha.Black.30}',
  'colorNeutralBackgroundSubtleInvertedSelectedLight': '{Colors.Alpha.Black.20}',
  'colorNeutralBackgroundTransparentRestLight': '{Colors.Alpha.White.0}',
  'colorNeutralBackgroundTransparentHoverLight': '{Colors.Alpha.White.0}',
  'colorNeutralBackgroundTransparentPressedLight': '{Colors.Alpha.White.0}',
  'colorNeutralBackgroundTransparentSelectedLight': '{Colors.Alpha.White.0}',
  'colorNeutralBackgroundDisabledRestLight': '{Colors.Neutral.Grey-80}',
  'colorNeutralBackgroundStencil1RestLight': '{Colors.Neutral.Grey-70}',
  'colorNeutralBackgroundStencil2RestLight': '{Colors.Neutral.Grey-90}',
  'colorNeutralBackgroundOverlayRestLight': '{Colors.Alpha.Black.40}',
  'colorNeutralBackgroundOverlayScrollbarRestLight': '{Colors.Alpha.Black.50}',
  'colorNeutralForeground1RestPrimaryTextLight': '{Brand-10}',
  'colorNeutralForeground1HoverLight': '{Brand-30}',
  'colorNeutralForeground1PressedLight': '{Brand-30}',
  'colorNeutralForeground1SelectedLight': '{Brand-30}',
  'colorNeutralForeground2RestSecondaryTextLight': '{Colors.Neutral.Grey-12}',
  'colorNeutralForeground2HoverLight': '{Colors.Neutral.Grey-6}',
  'colorNeutralForeground2PressedLight': '{Colors.Neutral.Grey-6}',
  'colorNeutralForeground2SelectedLight': '{Colors.Neutral.Grey-6}',
  'colorNeutralForeground2BrandHoverLight': '{Brand-50}',
  'colorNeutralForeground2BrandPressedLight': '{Brand-40}',
  'colorNeutralForeground2BrandSelectedLight': '{Brand-30}',
  'colorNeutralForeground2BrandRestLight': '{Brand-60}',
  'colorNeutralForeground2LinkRestLight': '{Brand-60}',
  'colorNeutralForeground2LinkHoverLight': '{Brand-50}',
  'colorNeutralForeground2LinkPressedLight': '{Brand-40}',
  'colorNeutralForeground2LinkSelectedLight': '{Brand-30}',
  'colorNeutralForeground4RestLight': '{Colors.Neutral.Grey-30}',
  'colorNeutralForegroundDisabled2RestLight': '{Colors.Neutral.Grey-60}',
  'colorNeutralForegroundDisabledRestLight': '{Colors.Neutral.Grey-50}',
  'colorNeutralForegroundStaticInvertedRestLight': '{Colors.Neutral.White}',
  'colorNeutralForegroundInverted1RestLight': '{Colors.Neutral.White}',
  'colorNeutralForegroundInverted1HoverLight': '{Colors.Neutral.Grey-80}',
  'colorNeutralForegroundInverted1PressedLight': '{Colors.Neutral.Grey-70}',
  'colorNeutralForegroundInverted1SelectedLight': '{Colors.Neutral.Grey-60}',
  'colorNeutralForegroundInverted2RestLight': '{Colors.Neutral.White}',
  'colorNeutralForegroundInvertedDisabledRestLight': '{Colors.Alpha.White.40}',
  'colorNeutralForegroundInvertedLinkRestLight': '{Colors.Neutral.White}',
  'colorNeutralForegroundInvertedLinkHoverLight': '{Colors.Neutral.Grey-90}',
  'colorNeutralForegroundInvertedLinkPressedLight': '{Colors.Neutral.Grey-80}',
  'colorNeutralForegroundInvertedLinkSelectedLight': '{Colors.Neutral.Grey-70}',
  'colorNeutralForegroundOnBrandRestLight': '{Colors.Neutral.White}',
  'colorNeutralStroke1RestLight': '{Colors.Neutral.Grey-70}',
  'colorNeutralStroke1HoverLight': '{Colors.Neutral.Grey-60}',
  'colorNeutralStroke1PressedLight': '{Colors.Neutral.Grey-50}',
  'colorNeutralStroke1SelectedLight': '{Colors.Neutral.Grey-40}',
  'colorNeutralStroke2RestLight': '{Colors.Grey.White}',
  'colorNeutralStroke3RestLight': '{Colors.Neutral.Grey-50}',
  'colorNeutralStrokeAlpha1RestLight': '{Colors.Alpha.Black.5}',
  'colorNeutralStrokeAlpha2RestLight': '{Colors.Alpha.White.20}',
  'colorNeutralStrokeSubtleRestLight': '#f5f4f2',
  'colorNeutralStrokeonBrand1RestLight': '{Brand-60}',
  'colorNeutralStrokeonBrand2RestLight': '{Colors.Neutral.White}',
  'colorNeutralStrokeAccessibleRestLight': '{Brand-60}',
  'colorNeutralStrokeAccessibleHoverLight': '{Brand-50}',
  'colorNeutralStrokeAccessiblePressedLight': '{Brand-40}',
  'colorNeutralStrokeAccessibleSelectedLight': '{Brand-30}',
  'colorNeutralStrokeFocus1RestLight': '{Brand-60}',
  'colorNeutralStrokeFocus2RestLight': '{Colors.Grey.White}',
  'colorNeutralStrokeTransparentInteractiveRestLight': '{Colors.Alpha.White.0}',
  'colorNeutralStrokeTransparentDisabledRestLight': '{Colors.Alpha.White.0}',
  'colorNeutralStrokeTransparentRestLight': '{Colors.Alpha.White.0}',
  'colorNeutralStrokeDisabledRestLight': '{Colors.Neutral.Grey-70}',
  'colorNeutralStrokeDisabledInvertedRestLight': '{Colors.Alpha.White.40}',
  'colorBrandBackground1RestLight': '{Brand-60}',
  'colorBrandBackground1HoverLight': '{Brand-50}',
  'colorBrandBackground1PressedLight': '{Brand-40}',
  'colorBrandBackground1SelectedLight': '{Brand-30}',
  'colorBrandBackground2RestLight': '{Brand-10}',
  'colorBrandBackground2HoverLight': '{Brand-110}',
  'colorBrandBackground2PressedLight': '{Brand-100}',
  'colorBrandBackground3RestLight': '{Brand-120}',
  'colorBrandBackgroundInvertedRestLight': '{Colors.Neutral.White}',
  'colorBrandBackgroundInvertedHoverLight': '{Brand-120}',
  'colorBrandBackgroundInvertedPressedLight': '{Brand-130}',
  'colorBrandBackgroundInvertedSelectedLight': '{Brand-100}',
  'colorBrandBackgroundStaticRestLight': '{Brand-60}',
  'colorBrandBackgroundCompoundRestLight': '{Brand-60}',
  'colorBrandBackgroundCompoundHoverLight': '{Brand-50}',
  'colorBrandBackgroundCompoundPressedLight': '{Brand-40}',
  'colorBrandForeground1RestLight': '{Brand-60}',
  'colorBrandForeground1HoverLight': '{Brand-50}',
  'colorBrandForeground1PressedLight': '{Brand-40}',
  'colorBrandForeground1SelectedLight': '{Brand-30}',
  'colorBrandForeground2RestLight': '{Brand-80}',
  'colorBrandForeground2HoverLight': '{Brand-60}',
  'colorBrandForeground2PressedLight': '{Brand-30}',
  'colorBrandForegroundLinkRestLight': '{Brand-60}',
  'colorBrandForegroundLinkHoverLight': '{Brand-50}',
  'colorBrandForegroundLinkPressedLight': '{Brand-40}',
  'colorBrandForegroundLinkSelectedLight': '{Brand-30}',
  'colorBrandForegroundInvertedRestLight': '{Brand-100}',
  'colorBrandForegroundInvertedHoverLight': '{Brand-110}',
  'colorBrandForegroundInvertedPressedLight': '{Brand-100}',
  'colorBrandForegroundOnLightRestLight': '{Brand-80}',
  'colorBrandForegroundOnLightHoverLight': '{Brand-70}',
  'colorBrandForegroundOnLightPressedLight': '{Brand-50}',
  'colorBrandForegroundOnLightSelectedLight': '{Brand-60}',
  'colorBrandForegroundCompoundRestLight': '{Brand-60}',
  'colorBrandForegroundCompoundHoverLight': '{Brand-50}',
  'colorBrandForegroundCompoundPressedLight': '{Brand-40}',
  'colorBrandStroke1RestLight': '{Brand-60}',
  'colorBrandStroke1HoverLight': '{Brand-50}',
  'colorBrandStroke1PressedLight': '{Brand-40}',
  'colorBrandStroke1SelectedLight': '{Brand-30}',
  'colorBrandStroke2RestLight': '{Brand-10}',
  'colorBrandStroke2ContrastRestLight': '{Brand-110}',
  'colorBrandStroke3RestLight': '{Brand-90}',
  'colorBrandStrokeCompoundRestLight': '{Brand-60}',
  'colorBrandStrokeCompoundHoverLight': '{Brand-50}',
  'colorBrandStrokeCompoundPressedLight': '{Brand-40}',
  'colorStatusDangerBackground1RestLight': '{Colors.Shared.Cranberry.Tint 60}',
  'colorStatusDangerBackground3RestLight': '{Colors.Shared.Cranberry.Primary}',
  'colorStatusDangerForeground1RestLight': '{Colors.Shared.Cranberry.Primary}',
  'colorStatusDangerForeground3RestLight': '{Colors.Neutral.White}',
  'colorStatusDangerStroke1RestLight': '{Colors.Shared.Cranberry.Primary}',
  'colorStatusDangerStroke2RestLight': '{Colors.Shared.Cranberry.Tint 30}',
  'colorStatusSuccessBackground1RestLight': '{Colors.Shared.Green.Tint 60}',
  'colorStatusSuccessBackground3RestLight': '{Colors.Shared.Green.Primary}',
  'colorStatusSuccessForeground1RestLight': '{Colors.Shared.Green.Primary}',
  'colorStatusSuccessForeground3RestLight': '{Colors.Neutral.White}',
  'colorStatusSuccessStroke1RestLight': '{Colors.Shared.Green.Primary}',
  'colorStatusSuccessStroke2RestLight': '{Colors.Shared.Green.Tint 30}',
  'colorStatusWarningBackground1RestLight': '{Colors.Shared.Orange.Tint 60}',
  'colorStatusWarningBackground3RestLight': '{Colors.Shared.Orange.Primary}',
  'colorStatusWarningForeground1RestLight': '{Colors.Shared.Orange.Primary}',
  'colorStatusWarningForeground3RestLight': '{Colors.Neutral.White}',
  'colorStatusWarningStroke1RestLight': '{Colors.Shared.Orange.Primary}',
  'colorStatusWarningStroke2RestLight': '{Colors.Shared.Orange.Tint 30}',
  'colorStatusOofForeground3RestLight': '{Colors.Shared.Berry.Primary}',
  'colorStatusAwayBackground3RestLight': '{Colors.Shared.Marigold.Primary}',
  'colorStatusAvailableForeground3RestLight': '{Colors.Shared.Light green.Primary}',
  'colorStatusGenericAnchorBackground2RestLight': '{Colors.Shared.Anchor.Tint 40}',
  'colorStatusGenericAnchorForeground2RestLight': '{Colors.Shared.Anchor.Shade 30}',
  'colorStatusGenericAnchorStrokeActiveRestLight': '{Colors.Shared.Anchor.Primary}',
  'colorStatusGenericInformationBackground1RestLight': '{Colors.Shared.Information.Tint 60}',
  'colorStatusGenericInformationBackground1HoverLight': '{Colors.Shared.Information.Tint 50}',
  'colorStatusGenericInformationBackground1PressedLight': '{Colors.Shared.Information.Tint 40}',
  'colorStatusGenericInformationStroke1RestLight': '{Colors.Shared.Information.Primary}',
  'colorStatusGenericInformationStroke2RestLight': '{Colors.Shared.Information.Tint 30}',
  'colorStatusGenericInformationStroke2HoverLight': '{Colors.Shared.Information.Tint 20}',
  'colorStatusGenericInformationStroke2PressedLight': '{Colors.Shared.Information.Tint 10}',
  'colorStatusGenericInformationForegroundRestLight': '{Colors.Shared.Information.Primary}',
  'colorStatusGenericInformationForegroundHoverLight': '{Colors.Shared.Information.Shade 10}',
  'colorStatusGenericInformationForegroundPressedLight': '{Colors.Shared.Information.Shade 20}',
  'colorStatusSevereBackground1RestLight': '{Colors.Shared.Dark Orange.Tint 60}',
  'colorStatusSevereBackground3RestLight': '{Colors.Shared.Dark Orange.Primary}',
  'colorStatusSevereForeground1RestLight': '{Colors.Shared.Dark Orange.Primary}',
  'colorStatusSevereForeground3RestLight': '{Colors.Neutral.White}',
  'colorStatusSevereStroke1RestLight': '{Colors.Shared.Dark Orange.Primary}',
  'colorStatusSevereStroke2RestLight': '{Colors.Shared.Dark Orange.Tint 30}',
  'colorShadowambientLight': '#0000001f',
  'colorShadowambientlighterLight': '#0000000f',
  'colorShadowambientdarkerLight': '#00000033',
  'colorShadowbrandambientLight': '#00000040',
  'colorShadowkeyLight': '#00000024',
  'colorShadowkeylighterLight': '#00000012',
  'colorShadowkeydarkerLight': '#0000003d',
  'colorShadowbrandkeyLight': '#0000004d',
  'colorNeutralBackground1RestDark': '{Colors.Neutral.Black}',
  'colorNeutralBackground1HoverDark': '{Colors.Neutral.Grey-10}',
  'colorNeutralBackground1PressedDark': '{Colors.Neutral.Grey-12}',
  'colorNeutralBackground1SelectedDark': '{Colors.Neutral.Grey-8}',
  'colorNeutralBackground2RestDark': '{Colors.Neutral.Grey-6}',
  'colorNeutralBackground3RestDark': '{Colors.Neutral.Grey-12}',
  'colorNeutralBackground3HoverDark': '{Colors.Neutral.Grey-10}',
  'colorNeutralBackground3PressedDark': '{Colors.Neutral.Grey-10}',
  'colorNeutralBackground4RestDark': '{Colors.Neutral.Grey-90}',
  'colorNeutralBackground4HoverDark': '{Colors.Neutral.Grey-70}',
  'colorNeutralBackground4PressedDark': '{Colors.Neutral.Grey-60}',
  'colorNeutralBackground5RestDark': '{Colors.Neutral.Grey-90}',
  'colorNeutralBackground6RestDark': '{Colors.Neutral.Grey-20}',
  'colorNeutralBackgroundInvertedRestDark': '{Colors.Neutral.White}',
  'colorNeutralBackgroundInvertedDisabledRestDark': '{Colors.Alpha.White.10}',
  'colorNeutralBackgroundAlpha1RestDark': '{Colors.Alpha.Brand-10.50}',
  'colorNeutralBackgroundAlpha2RestDark': '{Colors.Alpha.Black.70}',
  'colorNeutralBackgroundStaticRestDark': '{Colors.Neutral.White}',
  'colorNeutralBackgroundSubtleRestDark': '{Colors.Alpha.Black.0}',
  'colorNeutralBackgroundSubtleHoverDark': '{Colors.Neutral.Grey-80}',
  'colorNeutralBackgroundSubtlePressedDark': '{Colors.Neutral.Grey-70}',
  'colorNeutralBackgroundSubtleSelectedDark': '{Colors.Neutral.Grey-90}',
  'colorNeutralBackgroundSubtleLightAlphaHoverDark': '#242424cc',
  'colorNeutralBackgroundSubtleLightAlphaPressedDark': '#24242480',
  'colorNeutralBackgroundSubtleLightAlphaSelectedDark': '{Colors.Alpha.Black.0}',
  'colorNeutralBackgroundSubtleInvertedRestDark': '{Colors.Alpha.Black.0}',
  'colorNeutralBackgroundSubtleInvertedHoverDark': '{Colors.Alpha.Black.10}',
  'colorNeutralBackgroundSubtleInvertedPressedDark': '{Colors.Alpha.Black.30}',
  'colorNeutralBackgroundSubtleInvertedSelectedDark': '{Colors.Alpha.Black.20}',
  'colorNeutralBackgroundTransparentRestDark': '{Colors.Alpha.Black.0}',
  'colorNeutralBackgroundTransparentHoverDark': '{Colors.Alpha.Black.0}',
  'colorNeutralBackgroundTransparentPressedDark': '{Colors.Alpha.Black.0}',
  'colorNeutralBackgroundTransparentSelectedDark': '{Colors.Alpha.Black.0}',
  'colorNeutralBackgroundDisabledRestDark': '{Colors.Neutral.Grey-8}',
  'colorNeutralBackgroundStencil1RestDark': '#575757',
  'colorNeutralBackgroundStencil2RestDark': '{Colors.Neutral.Grey-20}',
  'colorNeutralBackgroundOverlayRestDark': '{Colors.Alpha.Black.50}',
  'colorNeutralBackgroundOverlayScrollbarRestDark': '{Colors.Alpha.White.60}',
  'colorNeutralForeground1RestPrimaryTextDark': '{Colors.Neutral.White}',
  'colorNeutralForeground1HoverDark': '{Colors.Neutral.White}',
  'colorNeutralForeground1PressedDark': '{Colors.Neutral.White}',
  'colorNeutralForeground1SelectedDark': '{Colors.Neutral.White}',
  'colorNeutralForeground2RestSecondaryTextDark': '{Colors.Neutral.White}',
  'colorNeutralForeground2HoverDark': '{Colors.Neutral.White}',
  'colorNeutralForeground2PressedDark': '{Colors.Neutral.White}',
  'colorNeutralForeground2SelectedDark': '{Colors.Neutral.White}',
  'colorNeutralForeground2BrandHoverDark': '{Brand-100}',
  'colorNeutralForeground2BrandPressedDark': '{Brand-90}',
  'colorNeutralForeground2BrandSelectedDark': '{Brand-100}',
  'colorNeutralForeground2BrandRestDark': '{Brand-100}',
  'colorNeutralForeground2LinkRestDark': '{Colors.Neutral.White}',
  'colorNeutralForeground2LinkHoverDark': '{Colors.Neutral.White}',
  'colorNeutralForeground2LinkPressedDark': '{Colors.Neutral.White}',
  'colorNeutralForeground2LinkSelectedDark': '{Colors.Neutral.White}',
  'colorNeutralForeground4RestDark': '{Colors.Neutral.Grey-60}',
  'colorNeutralForegroundDisabled2RestDark': '{Colors.Neutral.Grey-60}',
  'colorNeutralForegroundDisabledRestDark': '{Colors.Neutral.Grey-50}',
  'colorNeutralForegroundStaticInvertedRestDark': '{Colors.Neutral.White}',
  'colorNeutralForegroundInverted1RestDark': '#242424',
  'colorNeutralForegroundInverted1HoverDark': '#242424',
  'colorNeutralForegroundInverted1PressedDark': '#242424',
  'colorNeutralForegroundInverted1SelectedDark': '#242424',
  'colorNeutralForegroundInverted2RestDark': '#242424',
  'colorNeutralForegroundInvertedDisabledRestDark': '{Colors.Alpha.White.40}',
  'colorNeutralForegroundInvertedLinkRestDark': '{Colors.Neutral.White}',
  'colorNeutralForegroundInvertedLinkHoverDark': '{Colors.Neutral.White}',
  'colorNeutralForegroundInvertedLinkPressedDark': '{Colors.Neutral.White}',
  'colorNeutralForegroundInvertedLinkSelectedDark': '{Colors.Neutral.White}',
  'colorNeutralForegroundOnBrandRestDark': '{Colors.Neutral.White}',
  'colorNeutralStroke1RestDark': '{Colors.Neutral.Grey-40}',
  'colorNeutralStroke1HoverDark': '{Colors.Neutral.Grey-40}',
  'colorNeutralStroke1PressedDark': '{Colors.Neutral.Grey-40}',
  'colorNeutralStroke1SelectedDark': '{Colors.Neutral.Grey-40}',
  'colorNeutralStroke2RestDark': '{Colors.Grey.White}',
  'colorNeutralStroke3RestDark': '{Colors.Neutral.Grey-50}',
  'colorNeutralStrokeAlpha1RestDark': '{Colors.Alpha.White.10}',
  'colorNeutralStrokeAlpha2RestDark': '{Colors.Alpha.White.20}',
  'colorNeutralStrokeSubtleRestDark': '#f5f4f2',
  'colorNeutralStrokeonBrand1RestDark': '{Colors.Neutral.White}',
  'colorNeutralStrokeonBrand2RestDark': '{Colors.Grey.White}',
  'colorNeutralStrokeAccessibleRestDark': '{Colors.Neutral.White}',
  'colorNeutralStrokeAccessibleHoverDark': '{Colors.Neutral.White}',
  'colorNeutralStrokeAccessiblePressedDark': '{Colors.Neutral.White}',
  'colorNeutralStrokeAccessibleSelectedDark': '{Colors.Neutral.White}',
  'colorNeutralStrokeFocus1RestDark': '{Colors.Neutral.Black}',
  'colorNeutralStrokeFocus2RestDark': '{Colors.Neutral.White}',
  'colorNeutralStrokeTransparentInteractiveRestDark': '{Colors.Alpha.White.0}',
  'colorNeutralStrokeTransparentDisabledRestDark': '{Colors.Alpha.White.0}',
  'colorNeutralStrokeTransparentRestDark': '{Colors.Alpha.White.0}',
  'colorNeutralStrokeDisabledRestDark': '{Colors.Neutral.Grey-70}',
  'colorNeutralStrokeDisabledInvertedRestDark': '{Colors.Alpha.White.40}',
  'colorBrandBackground1RestDark': '{Brand-60}',
  'colorBrandBackground1HoverDark': '{Brand-40}',
  'colorBrandBackground1PressedDark': '{Brand-30}',
  'colorBrandBackground1SelectedDark': '{Brand-20}',
  'colorBrandBackground2RestDark': '{Brand-20}',
  'colorBrandBackground2HoverDark': '{Brand-40}',
  'colorBrandBackground2PressedDark': '{Brand-10}',
  'colorBrandBackground3RestDark': '#ffffff',
  'colorBrandBackgroundInvertedRestDark': '{Colors.Neutral.White}',
  'colorBrandBackgroundInvertedHoverDark': '{Brand-120}',
  'colorBrandBackgroundInvertedPressedDark': '{Brand-130}',
  'colorBrandBackgroundInvertedSelectedDark': '{Brand-100}',
  'colorBrandBackgroundStaticRestDark': '{Brand-80}',
  'colorBrandBackgroundCompoundRestDark': '{Brand-100}',
  'colorBrandBackgroundCompoundHoverDark': '{Brand-110}',
  'colorBrandBackgroundCompoundPressedDark': '{Brand-90}',
  'colorBrandForeground1RestDark': '{Brand-100}',
  'colorBrandForeground1HoverDark': '{Brand-100}',
  'colorBrandForeground1PressedDark': '{Brand-100}',
  'colorBrandForeground1SelectedDark': '{Brand-100}',
  'colorBrandForeground2RestDark': '{Brand-110}',
  'colorBrandForeground2HoverDark': '{Brand-130}',
  'colorBrandForeground2PressedDark': '{Brand-100}',
  'colorBrandForegroundLinkRestDark': '{Brand-100}',
  'colorBrandForegroundLinkHoverDark': '{Brand-110}',
  'colorBrandForegroundLinkPressedDark': '{Brand-90}',
  'colorBrandForegroundLinkSelectedDark': '{Brand-100}',
  'colorBrandForegroundInvertedRestDark': '{Brand-80}',
  'colorBrandForegroundInvertedHoverDark': '{Brand-70}',
  'colorBrandForegroundInvertedPressedDark': '{Brand-60}',
  'colorBrandForegroundOnLightRestDark': '{Brand-70}',
  'colorBrandForegroundOnLightHoverDark': '{Brand-70}',
  'colorBrandForegroundOnLightPressedDark': '{Brand-50}',
  'colorBrandForegroundOnLightSelectedDark': '{Brand-60}',
  'colorBrandForegroundCompoundRestDark': '{Brand-100}',
  'colorBrandForegroundCompoundHoverDark': '{Brand-110}',
  'colorBrandForegroundCompoundPressedDark': '{Brand-90}',
  'colorBrandStroke1RestDark': '{Brand-100}',
  'colorBrandStroke1HoverDark': '#2886de',
  'colorBrandStroke1PressedDark': '{Brand-70}',
  'colorBrandStroke1SelectedDark': '{Brand-70}',
  'colorBrandStroke2RestDark': '{Brand-50}',
  'colorBrandStroke2ContrastRestDark': '{Brand-60}',
  'colorBrandStroke3RestDark': '#ffffff',
  'colorBrandStrokeCompoundRestDark': '{Brand-100}',
  'colorBrandStrokeCompoundHoverDark': '{Brand-110}',
  'colorBrandStrokeCompoundPressedDark': '{Brand-90}',
  'colorStatusDangerBackground1RestDark': '{Colors.Neutral.White}',
  'colorStatusDangerBackground3RestDark': '{Colors.Shared.Cranberry.Primary}',
  'colorStatusDangerForeground1RestDark': '{Colors.Shared.Cranberry.Tint 30}',
  'colorStatusDangerForeground3RestDark': '{Colors.Neutral.White}',
  'colorStatusDangerStroke1RestDark': '{Colors.Shared.Cranberry.Primary}',
  'colorStatusDangerStroke2RestDark': '{Colors.Shared.Cranberry.Tint 30}',
  'colorStatusSuccessBackground1RestDark': '{Colors.Shared.Green.Tint 60}',
  'colorStatusSuccessBackground3RestDark': '{Colors.Shared.Green.Primary}',
  'colorStatusSuccessForeground1RestDark': '{Colors.Shared.Green.Primary}',
  'colorStatusSuccessForeground3RestDark': '{Colors.Neutral.White}',
  'colorStatusSuccessStroke1RestDark': '{Colors.Shared.Green.Primary}',
  'colorStatusSuccessStroke2RestDark': '{Colors.Shared.Green.Tint 30}',
  'colorStatusWarningBackground1RestDark': '{Colors.Shared.Orange.Tint 60}',
  'colorStatusWarningBackground3RestDark': '{Colors.Shared.Orange.Primary}',
  'colorStatusWarningForeground1RestDark': '{Colors.Shared.Orange.Primary}',
  'colorStatusWarningForeground3RestDark': '{Colors.Neutral.White}',
  'colorStatusWarningStroke1RestDark': '{Colors.Shared.Orange.Primary}',
  'colorStatusWarningStroke2RestDark': '{Colors.Shared.Orange.Tint 30}',
  'colorStatusOofForeground3RestDark': '{Colors.Shared.Berry.Tint 20}',
  'colorStatusAwayBackground3RestDark': '{Colors.Shared.Marigold.Primary}',
  'colorStatusAvailableForeground3RestDark': '{Colors.Shared.Light green.Primary}',
  'colorStatusGenericAnchorBackground2RestDark': '{Colors.Shared.Anchor.Shade 30}',
  'colorStatusGenericAnchorForeground2RestDark': '{Colors.Shared.Anchor.Tint 40}',
  'colorStatusGenericAnchorStrokeActiveRestDark': '{Colors.Shared.Anchor.Tint 30}',
  'colorStatusGenericInformationBackground1RestDark': '#ffffff',
  'colorStatusGenericInformationBackground1HoverDark': '#ffffff',
  'colorStatusGenericInformationBackground1PressedDark': '#ffffff',
  'colorStatusGenericInformationStroke1RestDark': '#ffffff',
  'colorStatusGenericInformationStroke2RestDark': '#ffffff',
  'colorStatusGenericInformationStroke2HoverDark': '#ffffff',
  'colorStatusGenericInformationStroke2PressedDark': '#ffffff',
  'colorStatusGenericInformationForegroundRestDark': '#ffffff',
  'colorStatusGenericInformationForegroundHoverDark': '#ffffff',
  'colorStatusGenericInformationForegroundPressedDark': '#ffffff',
  'colorStatusSevereBackground1RestDark': '{Colors.Shared.Dark Orange.Tint 60}',
  'colorStatusSevereBackground3RestDark': '{Colors.Shared.Dark Orange.Primary}',
  'colorStatusSevereForeground1RestDark': '{Colors.Shared.Dark Orange.Primary}',
  'colorStatusSevereForeground3RestDark': '{Colors.Neutral.White}',
  'colorStatusSevereStroke1RestDark': '{Colors.Shared.Dark Orange.Primary}',
  'colorStatusSevereStroke2RestDark': '{Colors.Shared.Dark Orange.Tint 30}',
  'colorShadowambientDark': '#00000033',
  'colorShadowambientlighterDark': '#0000001f',
  'colorShadowambientdarkerDark': '#00000066',
  'colorShadowbrandambientDark': '#00000040',
  'colorShadowkeyDark': '#00000047',
  'colorShadowkeylighterDark': '#00000024',
  'colorShadowkeydarkerDark': '#0000007a',
  'colorShadowbrandkeyDark': '#0000004d'
};

// Utility functions
export const convertHexToRgba = (hex: string): string => {
  if (hex === 'transparent') return 'rgba(0, 0, 0, 0)';
  if (hex.startsWith('rgba')) return hex;
  
  const hexColor = hex.replace('#', '');
  const r = parseInt(hexColor.substring(0, 2), 16);
  const g = parseInt(hexColor.substring(2, 4), 16);
  const b = parseInt(hexColor.substring(4, 6), 16);
  const a = hexColor.length === 8 ? parseInt(hexColor.substring(6, 8), 16) / 255 : 1;
  return `rgba(${r}, ${g}, ${b}, ${a})`;
};

// Theme tokens object
export const brandThemeTokens = Object.entries(brandTheme).reduce((acc, [key, value]) => {
  if (value.startsWith('#')) {
    acc[key] = convertHexToRgba(value);
  } else {
    acc[key] = value;
  }
  return acc;
}, {} as Record<string, string>);
