import { Theme } from '@fluentui/react-components';

export const brandTheme: Theme = {
  'borderRadiusNone': '0px',
  'borderRadiusSmall': '2px',
  'borderRadiusMedium': '4px',
  'borderRadiusLarge': '6px',
  'borderRadiusXLarge': '8px',
  'borderRadiusCircular': '9999px',
  'fontSize0': '10px',
  'fontSize1': '12px',
  'fontSize2': '14px',
  'fontSize3': '16px',
  'fontSize4': '20px',
  'fontSize5': '24px',
  'fontSize6': '28px',
  'fontSize7': '32px',
  'fontSize8': '40px',
  'fontSize9': '48px',
  'fontSize10': '52px',
  'fontSize1000': '68px',
  'fontSizeBase100': '10px',
  'fontSizeBase200': '12px',
  'fontSizeBase300': '14px',
  'fontSizeBase400': '16px',
  'fontSizeBase500': '20px',
  'fontSizeBase600': '24px',
  'fontSizeBase700': '28px',
  'fontSizeBase800': '32px',
  'fontSizeBase900': '40px',
  'fontSizeBase980': '52px',
  'fontSizeBase920': '48px',
  'lineHeightBase100': '14px',
  'lineHeightBase200': '16px',
  'lineHeightBase300': '22px',
  'lineHeightBase400': '24px',
  'lineHeightBase500': '28px',
  'lineHeightBase600': '34px',
  'lineHeightBase700': '36px',
  'lineHeightBase800': '48px',
  'lineHeightBase900': '52px',
  'lineHeightbase1000': '92px',
  'lineHeightBase920': '64px',
  'lineHeightBase980': '70px',
  'fontFamilyBase': 'Segoe UI',
  'fontWeightRegular': '400',
  'fontWeightSemibold': '600',
  'fontWeightBold': '700',
  'fontWeightSemilight': '300',
  'fontWeightLight': '200',
  'strokeWidthNone': '0px',
  'strokeWidthThin': '1px',
  'strokeWidthThick': '2px',
  'strokeWidthThicker': '4px',
  'strokeWidthThickest': '6px',
  'spacingHorizontalNone': '0px',
  'spacingHorizontalXXS': '2px',
  'spacingHorizontalXS': '4px',
  'spacingHorizontalSNudge': '6px',
  'spacingHorizontalS': '8px',
  'spacingHorizontalMNudge': '12px',
  'spacingHorizontalM': '16px',
  'spacingHorizontalL': '32px',
  'spacingHorizontalXL': '48px',
  'spacingHorizontalXXL': '52px',
  'spacingHorizontalXXXL': '56px',
  'spacingHorizontalLNudge': '24px',
  'spacingHorizontalXXXXL': '64px',
  'spacingVerticalNone': '0px',
  'spacingVerticalXXS': '2px',
  'spacingVerticalXS': '4px',
  'spacingVerticalSNudge': '6px',
  'spacingVerticalS': '8px',
  'spacingVerticalMNudge': '12px',
  'spacingVerticalM': '16px',
  'spacingVerticalL': '32px',
  'spacingVerticalXL': '48px',
  'spacingVerticalXXL': '52px',
  'spacingVerticalXXXL': '56px',
  'spacingVerticalLNudge': '24px',
  'spacingVerticalXXXXL': '64px',
  'colorNeutralBackground1Rest': '{Colors.Neutral.Black}',
  'colorNeutralBackground1Hover': '{Colors.Neutral.Grey-10}',
  'colorNeutralBackground1Pressed': '{Colors.Neutral.Grey-12}',
  'colorNeutralBackground1Selected': '{Colors.Neutral.Grey-8}',
  'colorNeutralBackground2Rest': '{Colors.Neutral.Grey-6}',
  'colorNeutralBackground3Rest': '{Colors.Neutral.Grey-12}',
  'colorNeutralBackground3Hover': '{Colors.Neutral.Grey-10}',
  'colorNeutralBackground3Pressed': '{Colors.Neutral.Grey-10}',
  'colorNeutralBackground4Rest': '{Colors.Neutral.Grey-90}',
  'colorNeutralBackground4Hover': '{Colors.Neutral.Grey-70}',
  'colorNeutralBackground4Pressed': '{Colors.Neutral.Grey-60}',
  'colorNeutralBackground5Rest': '{Colors.Neutral.Grey-90}',
  'colorNeutralBackground6Rest': '{Colors.Neutral.Grey-20}',
  'colorNeutralBackgroundInvertedRest': '{Colors.Neutral.White}',
  'colorNeutralBackgroundInvertedDisabledRest': '{Colors.Alpha.White.10}',
  'colorNeutralBackgroundAlpha1Rest': '{Colors.Alpha.Brand-10.50}',
  'colorNeutralBackgroundAlpha2Rest': '{Colors.Alpha.Black.70}',
  'colorNeutralBackgroundStaticRest': '{Colors.Neutral.White}',
  'colorNeutralBackgroundSubtleRest': '{Colors.Alpha.Black.0}',
  'colorNeutralBackgroundSubtleHover': '{Colors.Neutral.Grey-80}',
  'colorNeutralBackgroundSubtlePressed': '{Colors.Neutral.Grey-70}',
  'colorNeutralBackgroundSubtleSelected': '{Colors.Neutral.Grey-90}',
  'colorNeutralBackgroundSubtleLightAlphaHover': '#242424cc',
  'colorNeutralBackgroundSubtleLightAlphaPressed': '#24242480',
  'colorNeutralBackgroundSubtleLightAlphaSelected': '{Colors.Alpha.Black.0}',
  'colorNeutralBackgroundSubtleInvertedRest': '{Colors.Alpha.Black.0}',
  'colorNeutralBackgroundSubtleInvertedHover': '{Colors.Alpha.Black.10}',
  'colorNeutralBackgroundSubtleInvertedPressed': '{Colors.Alpha.Black.30}',
  'colorNeutralBackgroundSubtleInvertedSelected': '{Colors.Alpha.Black.20}',
  'colorNeutralBackgroundTransparentRest': '{Colors.Alpha.Black.0}',
  'colorNeutralBackgroundTransparentHover': '{Colors.Alpha.Black.0}',
  'colorNeutralBackgroundTransparentPressed': '{Colors.Alpha.Black.0}',
  'colorNeutralBackgroundTransparentSelected': '{Colors.Alpha.Black.0}',
  'colorNeutralBackgroundDisabledRest': '{Colors.Neutral.Grey-8}',
  'colorNeutralBackgroundStencil1Rest': '#575757',
  'colorNeutralBackgroundStencil2Rest': '{Colors.Neutral.Grey-20}',
  'colorNeutralBackgroundOverlayRest': '{Colors.Alpha.Black.50}',
  'colorNeutralBackgroundOverlayScrollbarRest': '{Colors.Alpha.White.60}',
  'colorNeutralForeground1RestPrimaryText': '{Colors.Neutral.White}',
  'colorNeutralForeground1Hover': '{Colors.Neutral.White}',
  'colorNeutralForeground1Pressed': '{Colors.Neutral.White}',
  'colorNeutralForeground1Selected': '{Colors.Neutral.White}',
  'colorNeutralForeground2RestSecondaryText': '{Colors.Neutral.White}',
  'colorNeutralForeground2Hover': '{Colors.Neutral.White}',
  'colorNeutralForeground2Pressed': '{Colors.Neutral.White}',
  'colorNeutralForeground2Selected': '{Colors.Neutral.White}',
  'colorNeutralForeground2BrandHover': '{Brand-100}',
  'colorNeutralForeground2BrandPressed': '{Brand-90}',
  'colorNeutralForeground2BrandSelected': '{Brand-100}',
  'colorNeutralForeground2BrandRest': '{Brand-100}',
  'colorNeutralForeground2LinkRest': '{Colors.Neutral.White}',
  'colorNeutralForeground2LinkHover': '{Colors.Neutral.White}',
  'colorNeutralForeground2LinkPressed': '{Colors.Neutral.White}',
  'colorNeutralForeground2LinkSelected': '{Colors.Neutral.White}',
  'colorNeutralForeground4Rest': '{Colors.Neutral.Grey-60}',
  'colorNeutralForegroundDisabled2Rest': '{Colors.Neutral.Grey-60}',
  'colorNeutralForegroundDisabledRest': '{Colors.Neutral.Grey-50}',
  'colorNeutralForegroundStaticInvertedRest': '{Colors.Neutral.White}',
  'colorNeutralForegroundInverted1Rest': '#242424',
  'colorNeutralForegroundInverted1Hover': '#242424',
  'colorNeutralForegroundInverted1Pressed': '#242424',
  'colorNeutralForegroundInverted1Selected': '#242424',
  'colorNeutralForegroundInverted2Rest': '#242424',
  'colorNeutralForegroundInvertedDisabledRest': '{Colors.Alpha.White.40}',
  'colorNeutralForegroundInvertedLinkRest': '{Colors.Neutral.White}',
  'colorNeutralForegroundInvertedLinkHover': '{Colors.Neutral.White}',
  'colorNeutralForegroundInvertedLinkPressed': '{Colors.Neutral.White}',
  'colorNeutralForegroundInvertedLinkSelected': '{Colors.Neutral.White}',
  'colorNeutralForegroundOnBrandRest': '{Colors.Neutral.White}',
  'colorNeutralStroke1Rest': '{Colors.Neutral.Grey-40}',
  'colorNeutralStroke1Hover': '{Colors.Neutral.Grey-40}',
  'colorNeutralStroke1Pressed': '{Colors.Neutral.Grey-40}',
  'colorNeutralStroke1Selected': '{Colors.Neutral.Grey-40}',
  'colorNeutralStroke2Rest': '{Colors.Grey.White}',
  'colorNeutralStroke3Rest': '{Colors.Neutral.Grey-50}',
  'colorNeutralStrokeAlpha1Rest': '{Colors.Alpha.White.10}',
  'colorNeutralStrokeAlpha2Rest': '{Colors.Alpha.White.20}',
  'colorNeutralStrokeSubtleRest': '#f5f4f2',
  'colorNeutralStrokeonBrand1Rest': '{Colors.Neutral.White}',
  'colorNeutralStrokeonBrand2Rest': '{Colors.Grey.White}',
  'colorNeutralStrokeAccessibleRest': '{Colors.Neutral.White}',
  'colorNeutralStrokeAccessibleHover': '{Colors.Neutral.White}',
  'colorNeutralStrokeAccessiblePressed': '{Colors.Neutral.White}',
  'colorNeutralStrokeAccessibleSelected': '{Colors.Neutral.White}',
  'colorNeutralStrokeFocus1Rest': '{Colors.Neutral.Black}',
  'colorNeutralStrokeFocus2Rest': '{Colors.Neutral.White}',
  'colorNeutralStrokeTransparentInteractiveRest': '{Colors.Alpha.White.0}',
  'colorNeutralStrokeTransparentDisabledRest': '{Colors.Alpha.White.0}',
  'colorNeutralStrokeTransparentRest': '{Colors.Alpha.White.0}',
  'colorNeutralStrokeDisabledRest': '{Colors.Neutral.Grey-70}',
  'colorNeutralStrokeDisabledInvertedRest': '{Colors.Alpha.White.40}',
  'colorBrandBackground1Rest': '{Brand-60}',
  'colorBrandBackground1Hover': '{Brand-40}',
  'colorBrandBackground1Pressed': '{Brand-30}',
  'colorBrandBackground1Selected': '{Brand-20}',
  'colorBrandBackground2Rest': '{Brand-20}',
  'colorBrandBackground2Hover': '{Brand-40}',
  'colorBrandBackground2Pressed': '{Brand-10}',
  'colorBrandBackground3Rest': '#ffffff',
  'colorBrandBackgroundInvertedRest': '{Colors.Neutral.White}',
  'colorBrandBackgroundInvertedHover': '{Brand-120}',
  'colorBrandBackgroundInvertedPressed': '{Brand-130}',
  'colorBrandBackgroundInvertedSelected': '{Brand-100}',
  'colorBrandBackgroundStaticRest': '{Brand-80}',
  'colorBrandBackgroundCompoundRest': '{Brand-100}',
  'colorBrandBackgroundCompoundHover': '{Brand-110}',
  'colorBrandBackgroundCompoundPressed': '{Brand-90}',
  'colorBrandForeground1Rest': '{Brand-100}',
  'colorBrandForeground1Hover': '{Brand-100}',
  'colorBrandForeground1Pressed': '{Brand-100}',
  'colorBrandForeground1Selected': '{Brand-100}',
  'colorBrandForeground2Rest': '{Brand-110}',
  'colorBrandForeground2Hover': '{Brand-130}',
  'colorBrandForeground2Pressed': '{Brand-100}',
  'colorBrandForegroundLinkRest': '{Brand-100}',
  'colorBrandForegroundLinkHover': '{Brand-110}',
  'colorBrandForegroundLinkPressed': '{Brand-90}',
  'colorBrandForegroundLinkSelected': '{Brand-100}',
  'colorBrandForegroundInvertedRest': '{Brand-80}',
  'colorBrandForegroundInvertedHover': '{Brand-70}',
  'colorBrandForegroundInvertedPressed': '{Brand-60}',
  'colorBrandForegroundOnLightRest': '{Brand-70}',
  'colorBrandForegroundOnLightHover': '{Brand-70}',
  'colorBrandForegroundOnLightPressed': '{Brand-50}',
  'colorBrandForegroundOnLightSelected': '{Brand-60}',
  'colorBrandForegroundCompoundRest': '{Brand-100}',
  'colorBrandForegroundCompoundHover': '{Brand-110}',
  'colorBrandForegroundCompoundPressed': '{Brand-90}',
  'colorBrandStroke1Rest': '{Brand-100}',
  'colorBrandStroke1Hover': '#2886de',
  'colorBrandStroke1Pressed': '{Brand-70}',
  'colorBrandStroke1Selected': '{Brand-70}',
  'colorBrandStroke2Rest': '{Brand-50}',
  'colorBrandStroke2ContrastRest': '{Brand-60}',
  'colorBrandStroke3Rest': '#ffffff',
  'colorBrandStrokeCompoundRest': '{Brand-100}',
  'colorBrandStrokeCompoundHover': '{Brand-110}',
  'colorBrandStrokeCompoundPressed': '{Brand-90}',
  'colorStatusDangerBackground1Rest': '{Colors.Neutral.White}',
  'colorStatusDangerBackground3Rest': '{Colors.Shared.Cranberry.Primary}',
  'colorStatusDangerForeground1Rest': '{Colors.Shared.Cranberry.Tint 30}',
  'colorStatusDangerForeground3Rest': '{Colors.Neutral.White}',
  'colorStatusDangerStroke1Rest': '{Colors.Shared.Cranberry.Primary}',
  'colorStatusDangerStroke2Rest': '{Colors.Shared.Cranberry.Tint 30}',
  'colorStatusSuccessBackground1Rest': '{Colors.Shared.Green.Tint 60}',
  'colorStatusSuccessBackground3Rest': '{Colors.Shared.Green.Primary}',
  'colorStatusSuccessForeground1Rest': '{Colors.Shared.Green.Primary}',
  'colorStatusSuccessForeground3Rest': '{Colors.Neutral.White}',
  'colorStatusSuccessStroke1Rest': '{Colors.Shared.Green.Primary}',
  'colorStatusSuccessStroke2Rest': '{Colors.Shared.Green.Tint 30}',
  'colorStatusWarningBackground1Rest': '{Colors.Shared.Orange.Tint 60}',
  'colorStatusWarningBackground3Rest': '{Colors.Shared.Orange.Primary}',
  'colorStatusWarningForeground1Rest': '{Colors.Shared.Orange.Primary}',
  'colorStatusWarningForeground3Rest': '{Colors.Neutral.White}',
  'colorStatusWarningStroke1Rest': '{Colors.Shared.Orange.Primary}',
  'colorStatusWarningStroke2Rest': '{Colors.Shared.Orange.Tint 30}',
  'colorStatusOofForeground3Rest': '{Colors.Shared.Berry.Tint 20}',
  'colorStatusAwayBackground3Rest': '{Colors.Shared.Marigold.Primary}',
  'colorStatusAvailableForeground3Rest': '{Colors.Shared.Light green.Primary}',
  'colorStatusGenericAnchorBackground2Rest': '{Colors.Shared.Anchor.Shade 30}',
  'colorStatusGenericAnchorForeground2Rest': '{Colors.Shared.Anchor.Tint 40}',
  'colorStatusGenericAnchorStrokeActiveRest': '{Colors.Shared.Anchor.Tint 30}',
  'colorStatusGenericInformationBackground1Rest': '#ffffff',
  'colorStatusGenericInformationBackground1Hover': '#ffffff',
  'colorStatusGenericInformationBackground1Pressed': '#ffffff',
  'colorStatusGenericInformationStroke1Rest': '#ffffff',
  'colorStatusGenericInformationStroke2Rest': '#ffffff',
  'colorStatusGenericInformationStroke2Hover': '#ffffff',
  'colorStatusGenericInformationStroke2Pressed': '#ffffff',
  'colorStatusGenericInformationForegroundRest': '#ffffff',
  'colorStatusGenericInformationForegroundHover': '#ffffff',
  'colorStatusGenericInformationForegroundPressed': '#ffffff',
  'colorStatusSevereBackground1Rest': '{Colors.Shared.Dark Orange.Tint 60}',
  'colorStatusSevereBackground3Rest': '{Colors.Shared.Dark Orange.Primary}',
  'colorStatusSevereForeground1Rest': '{Colors.Shared.Dark Orange.Primary}',
  'colorStatusSevereForeground3Rest': '{Colors.Neutral.White}',
  'colorStatusSevereStroke1Rest': '{Colors.Shared.Dark Orange.Primary}',
  'colorStatusSevereStroke2Rest': '{Colors.Shared.Dark Orange.Tint 30}',
  'colorShadowambient': '#00000033',
  'colorShadowambientlighter': '#0000001f',
  'colorShadowambientdarker': '#00000066',
  'colorShadowbrandambient': '#00000040',
  'colorShadowkey': '#00000047',
  'colorShadowkeylighter': '#00000024',
  'colorShadowkeydarker': '#0000007a',
  'colorShadowbrandkey': '#0000004d'
};

// Utility functions
export const convertHexToRgba = (hex: string): string => {
  if (hex === 'transparent') return 'rgba(0, 0, 0, 0)';
  if (hex.startsWith('rgba')) return hex;
  
  const hexColor = hex.replace('#', '');
  const r = parseInt(hexColor.substring(0, 2), 16);
  const g = parseInt(hexColor.substring(2, 4), 16);
  const b = parseInt(hexColor.substring(4, 6), 16);
  const a = hexColor.length === 8 ? parseInt(hexColor.substring(6, 8), 16) / 255 : 1;
  return `rgba(${r}, ${g}, ${b}, ${a})`;
};

// Theme tokens object
export const brandThemeTokens = Object.entries(brandTheme).reduce((acc, [key, value]) => {
  if (value.startsWith('#')) {
    acc[key] = convertHexToRgba(value);
  } else {
    acc[key] = value;
  }
  return acc;
}, {} as Record<string, string>);
