name: Token Pipeline

on:
  repository_dispatch:
    types: [design-tokens-updated]
  push:
    branches:
      - dev
      - main
    paths:
      - 'tokens/**'

jobs:
  process-tokens:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - uses: actions/setup-node@v3
        with:
          node-version: '20.9.0'

      - name: Install dependencies
        run: npm ci

      - name: Process Figma tokens
        if: github.event_name == 'repository_dispatch'
        run: |
          echo '${{ toJson(github.event.client_payload) }}' > figma-tokens.json
          node scripts/process-figma-tokens.js

      - name: Process tokens
        run: npx ts-node scripts/token-pipeline.ts

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "Update processed design tokens" || echo "No changes to commit"
          git push origin ${{ github.ref }} || echo "No changes to push"
