name: Sync Design Tokens

on:
  push:
    paths:
      - 'tokens/raw-themes.json'
    branches:
      - main
  workflow_dispatch:

jobs:
  sync-tokens:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PROCESS_PAT_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.9.0'
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm ci
          npm install -D typescript ts-node @types/node

      - name: Transform tokens
        run: |
          NODE_OPTIONS="--loader ts-node/esm" npx ts-node scripts/transform-tokens.ts

      - name: Check for changes
        id: git-check
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add -A
          git diff --cached --quiet || echo "changes=true" >> $GITHUB_OUTPUT

      - name: Create Pull Request
        if: steps.git-check.outputs.changes == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.PROCESS_PAT_TOKEN }}
          commit-message: 'chore: update design tokens'
          title: 'Update design tokens'
          body: |
            This PR updates the design tokens exported from Figma.
            
            Changes have been processed from `raw-themes.json` to create an updated `themes.json`.
            
            Please review the changes before merging.
          branch: 'token-studio-sync'
          base: 'main'
          labels: |
            automated
            design-tokens
          delete-branch: true