name: Sync Design Tokens

on:
  push:
    paths:
      - 'tokens/**'
    branches:
      - main
  workflow_dispatch:

jobs:
  sync-tokens:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PROCESS_PAT_TOKEN }}  # Use a Personal Access Token instead

      # ... (rest of your steps remain the same)

      - name: Create Pull Request
        if: steps.git-check.outputs.changes == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.PROCESS_PAT_TOKEN }}  # Use the same PAT here
          commit-message: 'chore: update design tokens'
          title: '🎨 Update design tokens'
          body: |
            This PR updates the design tokens with the latest changes from Figma.
            
            Changes include updates to:
            - Font tokens
            - Effect tokens
            - Tree indentation tokens
            - Popover size tokens
            - Card padding tokens
            - Button shape tokens
            - Badge shape tokens
            - Arrow position tokens
            - Typography tokens
            - Theme tokens
            - Global tokens
            - Brand tokens
            
            Please review the changes carefully before merging.
          branch: 'token-studio-sync'
          base: 'main'
          labels: |
            automated
            design-tokens
          delete-branch: true