# .github/workflows/token-sync.yml
name: Sync Design Tokens

on:
  push:
    paths:
      - 'tokens/**'
    branches:
      - main
  workflow_dispatch:

jobs:
  sync-tokens:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm ci
          npm install -D typescript ts-node @types/node

      - name: Transform tokens
        run: npx ts-node scripts/transform-tokens.ts

      - name: Check for changes
        id: git-check
        run: |
          git add -A
          git diff --cached --quiet || echo "changes=true" >> $GITHUB_OUTPUT

      - name: Create Pull Request
        if: steps.git-check.outputs.changes == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: 'chore: update theme tokens from Token Studio'
          title: '🎨 Update theme tokens from Token Studio'
          body: |
            This PR updates the theme tokens based on changes from Token Studio in Figma.
            
            - Automatically generated by Token Studio sync workflow
            - Please review the changes carefully before merging
          branch: 'token-studio-sync'
          base: 'main'
          labels: |
            automated
            design-tokens
          delete-branch: true