name: Sync Design Tokens

on:
  push:
    paths:
      - 'tokens/**'
    branches:
      - main
  workflow_dispatch:

jobs:
  sync-tokens:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.9.0'
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm ci
          npm install -D typescript ts-node @types/node @fluentui/react-components

      - name: Create necessary directories
        run: |
          mkdir -p src/theme

      - name: Transform tokens
        run: |
          npx ts-node scripts/transform-tokens.ts

      - name: Check for changes
        id: git-check
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add -A
          git diff --cached --quiet || echo "changes=true" >> $GITHUB_OUTPUT

      - name: Create Pull Request
        if: steps.git-check.outputs.changes == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: 'chore: update design tokens'
          title: '🎨 Update design tokens'
          body: |
            This PR updates the design tokens with the latest changes from Figma.
            
            Changes include updates to:
            - Font tokens
            - Effect tokens
            - Tree indentation tokens
            - Popover size tokens
            - Card padding tokens
            - Button shape tokens
            - Badge shape tokens
            - Arrow position tokens
            - Typography tokens
            - Theme tokens
            - Global tokens
            - Brand tokens
            
            Please review the changes carefully before merging.
          branch: 'token-studio-sync'
          base: 'main'
          labels: |
            automated
            design-tokens
          delete-branch: true